DROP TABLE IF EXISTS fleet;
CREATE TABLE Fleets (
  id BIGSERIAL PRIMARY KEY,
  fleet_name VARCHAR(50),
);

DROP TABLE IF EXISTS ships;
CREATE TABLE ships (
  id BIGSERIAL PRIMARY KEY,
  ship_name VARCHAR(50)
);

DROP TABLE IF EXISTS sailors;
CREATE TABLE sailors (
  id BIGSERIAL PRIMARY KEY,
  sailor_name VARCHAR(50),
  DOB DATE
);

DROP TABLE IF EXISTS duties;
CREATE TABLE duties (
  id BIGSERIAL PRIMARY KEY,
)

DROP TABLE IF EXISTS rank;
CREATE TABLE rank (
  id BIGSERIAL PRIMARY KEY,
)
